### PR TITLE
(Early Access) New look Website

### PR DESCRIPTION
**Pull request by futag**
Friendship end with bootstrap
now, tailwind is my best friend

Doc: https://tailwindcss.com/docs

### CODE REVIEW

**Comment by JustHumanz** [comment]
it had some Conflicting files, can you resolve it?

**Comment by JustHumanz** [comment]
let me test it on local first

**Comment by JustHumanz** [comment]
@yarndinasti can you show me how to run it ?

i already install the package `npm i` and run it as dev `npm run dev` but it shows noting with 404 return

Screenshot from 2022-02-11 01-51-13

also, i've already created a new branch(new-web-UI) for this PR so if you have something to change you can push to that branche

**Comment by futag** [comment]
Update node to latest lts

**Comment by JustHumanz** [comment]
my nodejs already in latest version

i think you forget to add index.html ?

Screenshot from 2022-02-11 15-23-15

here my steps
```
git clone https://github.com/JustHumanz/Go-Simp
cd Go-Simp
git checkout new-web-UI
cd service/new-web-vue
npm run build
```

**Comment by yarndinasti** [comment]
ok, now try again

**Comment by futag** [comment]
ok ,now try

**Comment by JustHumanz** [comment]
LGTM

**Comment by JustHumanz** [comment]
the new UI will be in `new-web-lets-go` brach, i can't marge into master for now

we need to test it first, after that we can marge into master and deploy it

anyway,thx mate

**Comment by JustHumanz** [comment]
@yarndinasti 
pls change this with your nickname

Screenshot 2022-02-13 at 19-18-57 Vite App

**Comment by futag** [comment]
I can't change it for now, because I want to finish the vtuber page first

**Comment by JustHumanz** [comment]
yeah sure,just let me know you already finish it and ready to deploy

**Pull request merged**
