### PR TITLE
Web v3

### PR DESCRIPTION
**Pull request by futag**
and changing old screenshot in readme

### CODE REVIEW

**Comment by JustHumanz** [comment]
damn

**Comment by JustHumanz** [comment]
LGTM

**Comment by JustHumanz** [comment]
Already deployed,thx for your hardwork   
love this new web <3


Screenshot 2022-03-18 at 18-52-51 Vtbot - A vtuber scheduler from Discord Server

**Comment by futag** [comment]
but some error in re memories and myholotv from migrate

**Comment by futag** [comment]
https://github.com/JustHumanz/Go-Simp/commit/1110884a78bf974ef29e6813c29de4ad1f4e7497 There is a fix that has been fixed

**Pull request merged**
