### PR TITLE
Updated ViViD VTuber information

### PR DESCRIPTION
**Pull request by dp247**
Courtesy of Yutyu#7878 from the unofficial ViViD Discord, some name fixes as well as fanbase names and BiliBili IDs for the newly added ViViD VTubers.

### CODE REVIEW

**Comment by JustHumanz** [comment]
LGTM

**Review by JustHumanz — COMMENTED** [review]
hy did `Anko` have another nickname?
i'm sorry but nickname `Anko` already used other vtuber

**Comment by dp247** [comment]
I see. Is "Fuwamochi Anko" okay to use instead?

**Comment by JustHumanz** [comment]
> I see. Is "Fuwamochi Anko" okay to use instead?

sadly can't,i'm not allowed space in nickname,well we can replace space with underscore if you want
like,`Fuwamochi_Anko` or `Anko_vivid` 
how about that?

**Pull request merged**
